# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus   = 2

    # Use VBoxManage to customize the VM. For example to change memory:
    # vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.network "forwarded_port", guest: 443, host: 4433

  config.vm.provision :docker
  config.vm.provision :shell, inline: "ps aux | grep 'sshd:' | awk '{print $2}' | sudo xargs kill"
  #config.vm.provision :ansible do |ansible|
    #ansible.playbook = "provisioning/playbook.yml"
  #end
end
